// src/lib/phone-countries.ts

export type PhoneCountry = {
    code: string;
    dialCode: string;
    label: string;
    flagClass: string;
};

export const preferredPhoneCountries: PhoneCountry[] = [
    { code: "TR", dialCode: "+90", label: "Türkiye", flagClass: "fi fi-tr" },
    { code: "US", dialCode: "+1", label: "United States", flagClass: "fi fi-us" },
    { code: "DE", dialCode: "+49", label: "Germany", flagClass: "fi fi-de" },
    { code: "RU", dialCode: "+7", label: "Russia", flagClass: "fi fi-ru" },
];

export const allPhoneCountries: PhoneCountry[] = [
    { code: "AF", dialCode: "+93", label: "Afghanistan", flagClass: "fi fi-af" },
    { code: "AL", dialCode: "+355", label: "Albania", flagClass: "fi fi-al" },
    { code: "DZ", dialCode: "+213", label: "Algeria", flagClass: "fi fi-dz" },
    { code: "AD", dialCode: "+376", label: "Andorra", flagClass: "fi fi-ad" },
    { code: "AO", dialCode: "+244", label: "Angola", flagClass: "fi fi-ao" },
    { code: "AR", dialCode: "+54", label: "Argentina", flagClass: "fi fi-ar" },
    { code: "AM", dialCode: "+374", label: "Armenia", flagClass: "fi fi-am" },
    { code: "AU", dialCode: "+61", label: "Australia", flagClass: "fi fi-au" },
    { code: "AT", dialCode: "+43", label: "Austria", flagClass: "fi fi-at" },
    { code: "AZ", dialCode: "+994", label: "Azerbaijan", flagClass: "fi fi-az" },
    { code: "BH", dialCode: "+973", label: "Bahrain", flagClass: "fi fi-bh" },
    { code: "BD", dialCode: "+880", label: "Bangladesh", flagClass: "fi fi-bd" },
    { code: "BY", dialCode: "+375", label: "Belarus", flagClass: "fi fi-by" },
    { code: "BE", dialCode: "+32", label: "Belgium", flagClass: "fi fi-be" },
    { code: "BA", dialCode: "+387", label: "Bosnia and Herzegovina", flagClass: "fi fi-ba" },
    { code: "BR", dialCode: "+55", label: "Brazil", flagClass: "fi fi-br" },
    { code: "BG", dialCode: "+359", label: "Bulgaria", flagClass: "fi fi-bg" },
    { code: "CA", dialCode: "+1", label: "Canada", flagClass: "fi fi-ca" },
    { code: "CL", dialCode: "+56", label: "Chile", flagClass: "fi fi-cl" },
    { code: "CN", dialCode: "+86", label: "China", flagClass: "fi fi-cn" },
    { code: "CO", dialCode: "+57", label: "Colombia", flagClass: "fi fi-co" },
    { code: "HR", dialCode: "+385", label: "Croatia", flagClass: "fi fi-hr" },
    { code: "CY", dialCode: "+357", label: "Cyprus", flagClass: "fi fi-cy" },
    { code: "CZ", dialCode: "+420", label: "Czech Republic", flagClass: "fi fi-cz" },
    { code: "DK", dialCode: "+45", label: "Denmark", flagClass: "fi fi-dk" },
    { code: "EG", dialCode: "+20", label: "Egypt", flagClass: "fi fi-eg" },
    { code: "EE", dialCode: "+372", label: "Estonia", flagClass: "fi fi-ee" },
    { code: "FI", dialCode: "+358", label: "Finland", flagClass: "fi fi-fi" },
    { code: "FR", dialCode: "+33", label: "France", flagClass: "fi fi-fr" },
    { code: "GE", dialCode: "+995", label: "Georgia", flagClass: "fi fi-ge" },
    { code: "GR", dialCode: "+30", label: "Greece", flagClass: "fi fi-gr" },
    { code: "HK", dialCode: "+852", label: "Hong Kong", flagClass: "fi fi-hk" },
    { code: "HU", dialCode: "+36", label: "Hungary", flagClass: "fi fi-hu" },
    { code: "IS", dialCode: "+354", label: "Iceland", flagClass: "fi fi-is" },
    { code: "IN", dialCode: "+91", label: "India", flagClass: "fi fi-in" },
    { code: "ID", dialCode: "+62", label: "Indonesia", flagClass: "fi fi-id" },
    { code: "IR", dialCode: "+98", label: "Iran", flagClass: "fi fi-ir" },
    { code: "IQ", dialCode: "+964", label: "Iraq", flagClass: "fi fi-iq" },
    { code: "IE", dialCode: "+353", label: "Ireland", flagClass: "fi fi-ie" },
    { code: "IL", dialCode: "+972", label: "Israel", flagClass: "fi fi-il" },
    { code: "IT", dialCode: "+39", label: "Italy", flagClass: "fi fi-it" },
    { code: "JP", dialCode: "+81", label: "Japan", flagClass: "fi fi-jp" },
    { code: "JO", dialCode: "+962", label: "Jordan", flagClass: "fi fi-jo" },
    { code: "KZ", dialCode: "+7", label: "Kazakhstan", flagClass: "fi fi-kz" },
    { code: "KW", dialCode: "+965", label: "Kuwait", flagClass: "fi fi-kw" },
    { code: "LV", dialCode: "+371", label: "Latvia", flagClass: "fi fi-lv" },
    { code: "LB", dialCode: "+961", label: "Lebanon", flagClass: "fi fi-lb" },
    { code: "LT", dialCode: "+370", label: "Lithuania", flagClass: "fi fi-lt" },
    { code: "LU", dialCode: "+352", label: "Luxembourg", flagClass: "fi fi-lu" },
    { code: "MY", dialCode: "+60", label: "Malaysia", flagClass: "fi fi-my" },
    { code: "MT", dialCode: "+356", label: "Malta", flagClass: "fi fi-mt" },
    { code: "MX", dialCode: "+52", label: "Mexico", flagClass: "fi fi-mx" },
    { code: "MD", dialCode: "+373", label: "Moldova", flagClass: "fi fi-md" },
    { code: "MC", dialCode: "+377", label: "Monaco", flagClass: "fi fi-mc" },
    { code: "ME", dialCode: "+382", label: "Montenegro", flagClass: "fi fi-me" },
    { code: "MA", dialCode: "+212", label: "Morocco", flagClass: "fi fi-ma" },
    { code: "NL", dialCode: "+31", label: "Netherlands", flagClass: "fi fi-nl" },
    { code: "NZ", dialCode: "+64", label: "New Zealand", flagClass: "fi fi-nz" },
    { code: "NO", dialCode: "+47", label: "Norway", flagClass: "fi fi-no" },
    { code: "OM", dialCode: "+968", label: "Oman", flagClass: "fi fi-om" },
    { code: "PK", dialCode: "+92", label: "Pakistan", flagClass: "fi fi-pk" },
    { code: "PL", dialCode: "+48", label: "Poland", flagClass: "fi fi-pl" },
    { code: "PT", dialCode: "+351", label: "Portugal", flagClass: "fi fi-pt" },
    { code: "QA", dialCode: "+974", label: "Qatar", flagClass: "fi fi-qa" },
    { code: "RO", dialCode: "+40", label: "Romania", flagClass: "fi fi-ro" },
    { code: "SA", dialCode: "+966", label: "Saudi Arabia", flagClass: "fi fi-sa" },
    { code: "RS", dialCode: "+381", label: "Serbia", flagClass: "fi fi-rs" },
    { code: "SG", dialCode: "+65", label: "Singapore", flagClass: "fi fi-sg" },
    { code: "SK", dialCode: "+421", label: "Slovakia", flagClass: "fi fi-sk" },
    { code: "SI", dialCode: "+386", label: "Slovenia", flagClass: "fi fi-si" },
    { code: "ZA", dialCode: "+27", label: "South Africa", flagClass: "fi fi-za" },
    { code: "KR", dialCode: "+82", label: "South Korea", flagClass: "fi fi-kr" },
    { code: "ES", dialCode: "+34", label: "Spain", flagClass: "fi fi-es" },
    { code: "SE", dialCode: "+46", label: "Sweden", flagClass: "fi fi-se" },
    { code: "CH", dialCode: "+41", label: "Switzerland", flagClass: "fi fi-ch" },
    { code: "TH", dialCode: "+66", label: "Thailand", flagClass: "fi fi-th" },
    { code: "TN", dialCode: "+216", label: "Tunisia", flagClass: "fi fi-tn" },
    { code: "UA", dialCode: "+380", label: "Ukraine", flagClass: "fi fi-ua" },
    { code: "AE", dialCode: "+971", label: "United Arab Emirates", flagClass: "fi fi-ae" },
    { code: "GB", dialCode: "+44", label: "United Kingdom", flagClass: "fi fi-gb" },
    { code: "UZ", dialCode: "+998", label: "Uzbekistan", flagClass: "fi fi-uz" },
];